import type { NextPage, GetServerSideProps } from 'next'
import { useEffect, useState, memo, useContext } from 'react'
import { getEnv } from '@/utils/env'
import LoadingContext from '@/context/loading'
import styles from '@/styles/Resume.module.css'
import Head from 'next/head'
import Intro from '@/components/Intro'
import Content from '@/components/Content'
import Experience from '@/components/Experience'
import { ExportPDF } from '@/components/Tool/'
import Loading from '@/components/Loading'

type Props = {
  resume: Resume
}

const Resume: NextPage<Props, {}> = (props: Props) => {
  const { resume } = props
  const { intros, skills, experience, evaluations, title } = resume
  const [formattedInfos, setFormattedInfos] = useState<Intro>()
  const loadingContext = useContext(LoadingContext)
  const [loading, setLoading] = useState<boolean>(loadingContext.loading)

  useEffect(() => {
    if (intros.length !== 0) {
      setFormattedInfos(intros.reduce((prev, cur) => {
        return {
          ...prev,
          ...cur
        }
      }, {}))
    }
  }, [intros])

  return (
    <div className={styles['resume']} id="resume">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles['resume-wrapper']}>
        <LoadingContext.Provider value={{
          loading,
          setLoading
        }}>
          { loading && <Loading /> }
          <div className="tools">
            <ExportPDF infos={formattedInfos} />
          </div>
          <Intro intros={intros} infos={formattedInfos} />
          <div className={styles['resume-content']}>
            <Experience experience={experience} />
            <Content {...skills} />
            <Content {...evaluations} />
          </div>
        </LoadingContext.Provider>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const host = getEnv('HOST')
  const port = getEnv('PORT')
  const route = getEnv('ROUTE')
  const res = await fetch(`${host}:${port}${route}/api/resume`)
  const resume = await res.json()
  return {
    props: {
      resume
    }
  }
}

export default memo(Resume)
