import type { NextPage, GetServerSideProps } from 'next'
import styles from '@/styles/Resume.module.css'
import Head from 'next/head'
import Intro from '@/components/Intro'
import Content from '@/components/Content'
import Experience from '@/components/Experience'
import Tool from '@/components/Tool/'

type Props = {
  resume: Resume
}

const Resume: NextPage<Props, {}> = (props: Props) => {
  const { resume } = props
  const { intros, skills, experiences, evaluations } = resume
  console.log(resume)
  return (
    <div className={styles['resume']}>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles['resume-wrapper']}>
        <Tool />
        <Intro intros={intros} />
        <div className={styles['resume-content']}>
          <Experience experiences={experiences} />
          <Content {...skills} />
          <Content {...evaluations} />
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/resume')
  const resume = await res.json()
  return {
    props: {
      resume
    }
  }
}

export default Resume
